FROM mcr.microsoft.com/devcontainers/base:ubuntu-22.04

RUN mkdir /newdir && \
    touch /newdir/newfile.txt

# RUN echo "https://mirror.tuna.tsinghua.edu.cn/alpine/v3.4/main" > /etc/apk/repositories  && \
#     echo "https://mirror.tuna.tsinghua.edu.cn/alpine/v3.4/community" >> /etc/apk/repositories  && \     
#     echo "https://mirror.tuna.tsinghua.edu.cn/alpine/edge/testing" >> /etc/apk/repositories       

# RUN chmod a+x ./deployment-service

# RUN mkdir -p /root/.ssh && \
#     cat >> /root/.ssh/config << 'EOF'
# Host github.com
# Hostname ssh.github.com
# Port 443
# EOF

# iiiii
# todo: asdf
# TODO:IIJKKKKKKJK asdf

# iiiiii
# asdfasdf
